resources:
  - name: be_gitRepo
    type: GitRepo
    configuration:
      path: mjmckay/java-backend
      gitProvider: mjmckay_github

  - name: fe_gitRepo
    type: GitRepo
    configuration:
      path: mjmckay/vue-frontend
      gitProvider: mjmckay_github

pipelines:
  - name: demo_application
    steps:
      - name: bld_backend
        type: MvnBuild
        configuration:
          sourceLocation: .
          mvnCommand: clean install -ntp
          configFileLocation: .
          configFileName: mvn-art-config
          inputResources:
            - name: be_gitRepo
          integrations:
            - name: artifactory
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "11"
        execution:
          onStart:
            - javac -version
            - mvn --version

      - name: bld_frontend
        type: NpmBuild
        configuration:
          npmArgs: --no-progress --no-audit
          sourceLocation: .
          repositoryName: demo-npm-virtual
          inputResources:
            - name: fe_gitRepo
          integrations:
            - name: artifactory

      - name: pack_frontend
        type: Bash
        configuration:
          inputSteps:
            - name: bld_frontend
          integrations:
            - name: artifactory
        execution:
          onStart:
            - export tempStateLocation="$step_tmp_dir/npmSourceState"
            - restore_run_files npmBuildInputGitRepo $tempStateLocation
            - pushd $tempStateLocation
            - npm run build
            - add_run_files $tempStateLocation/. npmBuildInputGitRepo

      - name: publish_frontend
        type: NpmPublish
        configuration:
          repositoryName: demo-npm-virtual
          inputSteps:
            - name: pack_frontend
          integrations:
            - name: artifactory
        execution:
          onStart:
            - export inputNpmBuildStepName="bld_frontend"

      - name: build_app
        type: Bash
        configuration:
          environmentVariables:
            dockerImageName: 35.224.208.129:8082/docker-local/app
            dockerImageTag: ${run_number}
          inputResources:
            - name: be_gitRepo
              trigger: false
          inputSteps:
            - name: bld_backend
            - name: publish_frontend
          integrations:
            - name: artifactory
        execution:
          onStart:
            - rm -rf $run_dir/workspace/jfrog
            - retry_command jfrog rt config --url $int_artifactory_url --user $int_artifactory_user --apikey $int_artifactory_apikey --interactive=false
            - pushd $res_be_gitRepo_resourcePath
            - add_run_variables buildStepName=${step_name}
            - add_run_variables ${step_name}_buildNumber=${run_number}
            - add_run_variables ${step_name}_buildName=${pipeline_name}
            - docker build --pull --no-cache -t $dockerImageName:$dockerImageTag --build-arg REGISTRY=${int_demoArt_url} .
            - jfrog rt bce $pipeline_name $run_number
            - jfrog rt docker-push 35.224.208.129:8082/docker-local/app:$run_number docker-local --build-name=$pipeline_name --build-number=$run_number
            - add_run_files /tmp/jfrog/. jfrog

